# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dc3536cbe8eae984c9284ac26d9ebcd6bed49418b890d9fbef30765dbb6c1cb0b76d6f1fee01ea2f5043a2c3bdcc7bb89ce398dbc9dff57ed44120f8cf270a6

test:
  secret_key_base: e241fc971a7a52037757ca0cdaac39c492056d2e5c7580443610dbf18bdb85a54576e852b6125700cf924100fae6a37589689762e50536d6961893cd3f2cfc2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
